### ISSUE TITLE
couldn't compile pronto-lcm-ros-translators following README.rst instruction

### ISSUE THREAD

**Issue by BryceeeeeChen** [ipab-slmc/pronto-distro#42]
Dr Fallon,
Thanks for making the code of pronto open source, it really help me better understand the state estimator on robot....
I found that some auto-generated header files in ros2lcm*.cpp were renamed or relocated to /bot_core (or they were just missing?) 
might need to change 
```
#include "lcmtypes/pronto/atlas_behavior_t.hpp"
#include "lcmtypes/pronto/force_torque_t.hpp"
#include "lcmtypes/pronto/atlas_state_t.hpp"
#include "lcmtypes/pronto/utime_t.hpp"
#include "lcmtypes/pronto/atlas_raw_imu_batch_t.hpp"
#include "lcmtypes/pronto/multisense_state_t.hpp"
```
to
```
#include "lcmtypes/pronto/behavior_t.hpp"
#include "lcmtypes/bot_core/force_torque_t.hpp"
#include "lcmtypes/bot_core/robot_state_t.hpp"
#include "lcmtypes/bot_core/utime_t.hpp"
#include "lcmtypes/bot_core/kvh_raw_imu_batch_t.hpp"
```
then make modifications on the instantiation of related messages.

cmakelist.txt 
`pods_use_pkg_config_packages(lcm2ros lcm lcmtypes_pronto-lcmtypes bot2-core)  
`
also might need to be changed to 
`pods_use_pkg_config_packages(ros2lcm lcm lcmtypes_pronto bot2-core eigen3) 
`

**Comment by mauricefallon** [comment]
Yes, you are right about all of this. I haven't been maintaining the ros2lcm translator because its intended as a **suggestion** to any one who wants to use Pronto with ROS. If you want to run it on your robot you will probably have different topics and sensors - so you will need your own custom translator.

In general its not difficult to adapt what exists as ROS and LCM both us similar data types - just a different protocol for transmission.

If you have fixes to the translator, please do push them back to me, thanks
